import type { Spell } from './types';

export const fireSpells: Spell[] = [
	{
		name: 'Flame Dart',
		school: 'Fire',
		tier: 0,
		desc: 'Deal 1d10 damage to any target within Range 8. Inflicts Smoldering on crit. High Levels: +5 damage every 5 levels.',
		actions: 1,
		roll: '1d10!',
	},
	{
		name: "Heart's Fire",
		school: 'Fire',
		tier: 0,
		desc: 'Give an ally within Range 4 an extra Action. Costs 1 mana when not your turn. High Levels: +1 Range every 5 levels.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Ignite',
		school: 'Fire',
		tier: 1,
		desc: 'Deal 4d10 damage to a Smoldering target within Range 8, ending the condition. Upcast: +10 damage.',
		actions: 2,
		roll: '4d10!',
	},
	{
		name: 'Enchant Weapon',
		school: 'Fire',
		tier: 2,
		desc: '(Concentration, 1min) A weapon you touch is enchanted with magical flame for 1 minute. It deals +KEY damage and inflicts Smoldering on crit. Upcast: +KEY damage.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Flame Barrier',
		school: 'Fire',
		tier: 3,
		desc: '(Reaction, when you would Defend) Defend for free, until the start of your next turn, melee attackers against you take KEY damage and gain Smoldering. Upcast: +KEY damage.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Pyroclasm',
		school: 'Fire',
		tier: 4,
		desc: 'Other creatures within Reach 3 of you take 2d20+10 damage on a failed DEX save, half on save. Smoldering creatures automatically fail. Upcast: +1 Reach, +2 damage.',
		actions: 3,
		roll: '2d20+10',
	},
	{
		name: 'Fiery Embrace',
		school: 'Fire',
		tier: 5,
		desc: '(Concentration, 1min) All other creatures within Reach 8 are Smoldering. While Smoldering this way, ALL damage Resistance is suppressed and Immunity is reduced to Resistance. Upcast: +30 ft. radius for each additional mana spent.',
		actions: 2,
		roll: '',
	},
	{
		name: 'Living Inferno',
		school: 'Fire',
		tier: 7,
		desc: 'You become a pillar of living flame. Until the end of your next turn gain the effects of Flame Barrier. At the end of this turn and your next turn, cast Pyroclasm for free. Upcast: +10 ft. speed for the duration for each additional mana spent.',
		actions: 3,
		roll: '',
	},
	{
		name: 'Dragonform',
		school: 'Fire',
		tier: 9,
		desc: 'Transform into a Huge dragon. Gain 3 actions, a fly speed of 12, LVL Armor, 10×LVL temp HP, and: • Tooth & Claw: Reach 2, 1d20+LVL damage (ignore armor). Inflicts Smoldering, ignores Armor. • Immolating Breath: Cone 8. DC 20 DEX save, [KEY]d6 damage, half on save. Smoldering targets fail. You can maintain this form for as long as the temp HP granted by this spell remains (max. 10 minutes). When it ends, you drop to 0 HP.',
		actions: 5,
		roll: '1d20!+[LVL]',
	},
];

export const iceSpells: Spell[] = [
	{
		name: 'Ice Lance',
		school: 'Ice',
		tier: 0,
		desc: 'Deal 1d6 cold or piercing damage to a target within Range 12. On hit: slowed. High Levels: +3 cold damage every 5 levels.',
		actions: 1,
		roll: '1d6!',
	},
	{
		name: 'Snowblind',
		school: 'Ice',
		tier: 0,
		desc: 'Deal 1d6 damage to single target withing Reach 1. On hit: Blinded until end of their next turn. High Levels: +3 damage every 5 levels.',
		actions: 1,
		roll: '1d6!',
	},
	{
		name: 'Frost Shield',
		school: 'Ice',
		tier: 1,
		desc: 'When attacked, gain 2×KEY temp HP and Defend for free. The ice melts and these temp HP are lost at the start of your next turn. Upcast: +2×KEY temp HP.',
		actions: 0,
		roll: '',
	},
	{
		name: 'Shatter',
		school: 'Ice',
		tier: 2,
		desc: 'Deal 3d6 damage to target within Range 12. If any die rolls max against a Hampered target, this counts as a crit. On crit: +20 damage. Upcast: Increase the result of any die by 1. +5 damage on crit.',
		actions: 2,
		roll: '3d6!',
	},
	{
		name: 'Cryosleep',
		school: 'Ice',
		tier: 3,
		desc: 'Creatures in a 2×2 area within Reach 12 are Dazed. On failed STR save, they fall asleep instead, becoming Incapacitated until their next two turns have passed, until damaged, or until an ally uses an action to wake them. Upcast: +1 area, +1 turn asleep.',
		actions: 2,
		roll: '',
	},
	{
		name: 'Rimeblades',
		school: 'Ice',
		tier: 4,
		desc: '(Concentration, 1 min) Conjure razor-sharp icy spikes in 5 contiguous spaces within Reach 12; this area is difficult terrain. Creatures that enter these spaces (or who are in the area when you conjure them) suffer 2d6 damage for each space they touch. Upcast: +1 space, +1 damage.',
		actions: 3,
		roll: '2d6!',
	},
	{
		name: 'Arctic Blast',
		school: 'Ice',
		tier: 5,
		desc: 'Deal 4d6 +10 damage in Cone 4. Area is difficult terrain until end of your next turn. Surviving creatures must make a STR save or be frozen (Restrained) until end of their next turn; creatures already Hampered are Incapacitated for 1 turn. Upcast: +1 Reach.',
		actions: 2,
		roll: '4d6!+10',
	},
	{
		name: 'Glacier Strike',
		school: 'Ice',
		tier: 8,
		desc: 'Deal d66 bludgeoning to creatures in 3×3 area within Range 12. Creatures adjacent to that area take half as much. The entire area becomes difficult terrain. Upcast: +1 initial area.',
		actions: 3,
		roll: 'd6,6',
	},
	{
		name: 'Arctic Annihilation',
		school: 'Ice',
		tier: 9,
		desc: 'Choose any number of objects or willing creatures within Reach 12 to encase in ice. They are Incapacitated and immune to damage and effects until start of next turn. All other creatures and objects within Reach take d66 damage. Surviving creatures must make STR save or be Incapacitated for 1 round. Must Safe Rest for 1 week before reusing.',
		actions: 3,
		roll: 'd66',
	},
];

export const radiantSpells: Spell[] = [
	{
		name: 'Rebuke',
		school: 'Radiant',
		tier: 0,
		desc: 'Deal 1d6 damage to a target within Reach 4, ignoring Armor, does not miss. Deal double damage against undead or cowardly (those Frightened, or behind cover). High Levels: +2 every 5 levels.',
		actions: 1,
		roll: '1d6!',
	},
	{
		name: 'True Strike',
		school: 'Radiant',
		tier: 0,
		desc: 'Give a creature within Reach 2 advantage on the next attack they make, until the end of their next turn. High Levels: +1 Reach every 5 levels.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Heal',
		school: 'Radiant',
		tier: 1,
		desc: 'Heal a creature 1d6+KEY HP within Reach 1. Upcast: Choose one: +1 Target, +4 Reach, +1d6 healing. If 5+ mana is spent, you may also heal 1 negative condition (e.g., Blind, Deaf, 1 Wound, etc.).',
		actions: 1,
		roll: '1d6+[KEY]',
	},
	{
		name: 'Summon Lifebinding Spirit',
		school: 'Radiant',
		tier: 1,
		desc: '(Shepherd Only) Call forth a spirit companion that faithfully follows you wherever you go. It is immune to damage and other harmful effects. It lasts until you cast it again, Safe Rest, or until it has healed a number of times equal to the mana spent to summon it. Upcast: Increases its die size by 1 (max d12), +1 healing use. Action: It attacks or heals a creature within Reach 4. It attacks for 1d6+WIL radiant damage (ignoring armor), or heals for the same amount.',
		actions: 1,
		roll: '1d6!+[WIL]',
		onlyFor: 'Shepherd',
	},
	{
		name: 'Warding Bond',
		school: 'Radiant',
		tier: 2,
		desc: 'Designate a willing creature as your ward for 1 minute. They take half damage from all attacks, you are attacked for the other half. Upcast: +1 creature.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Shield of Justice',
		school: 'Radiant',
		tier: 3,
		desc: '(Reaction, when you would defend.) Defend for free. You reflect Radiant damage back at the attacker equal to the amount blocked, ignoring Armor. Upcast: +5 Armor.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Condemn',
		school: 'Radiant',
		tier: 4,
		desc: 'Deal 30 damage to a creature within Reach 4, can only target a creature who has crit you or an ally since your last turn. Cannot be reduced by any means. The next attack against that enemy is made with advantage. Upcast: +1 reach, +1 advantage.',
		actions: 2,
		roll: '',
	},
	{
		name: 'Vengeance',
		school: 'Radiant',
		tier: 5,
		desc: 'Deal 1d100 damage to a creature within Reach 1 that attacked a dying ally or reduced one to 0 HP since your last turn. Upcast: +1 reach, roll with advantage.',
		actions: 2,
		roll: '1d100',
	},
	{
		name: 'Sacrifice',
		school: 'Radiant',
		tier: 6,
		desc: 'Reduce yourself to 0 HP. You can not have more than 0 HP until you Safe Rest. Heal a number of HP equal to your maximum HP, divided as you choose to any number of other creatures within Reach 4. You may revive a creature that has died in the past minute if you give them at least 20 HP (also healing 2 Wounds from them), provided they have not been revived with this spell before. Upcast: +4 Reach.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Redeem',
		school: 'Radiant',
		tier: 9,
		desc: '(Casting Time: 24 hours. Requires a diamond worth at least 10,000 gp which this spell consumes.) Revive any number of deceased creatures within 1 mile that have died in the past year, provided they have not died of old age or been revived with this spell before.',
		actions: -1,
		roll: '',
	},
];

export const necroticSpells: Spell[] = [
	{
		name: 'Shadow Blast',
		school: 'Necrotic',
		tier: -1,
		desc: '(Shadowmancer Only.) Deal 1d12+KEY damage to a target within Range 8, 1/round. Higher Levels: +1d12 every 5 levels.',
		actions: 1,
		roll: '1d12!+[KEY]',
		onlyFor: 'Shadowmancer',
	},
	{
		name: 'Summon Shadow',
		school: 'Necrotic',
		tier: -1,
		desc: '(Shadowmancer Only.) Summon a d12 shadow minion within Reach 1 (the maximum number of minions you can summon this way is equal to your INT or LVL, whichever is lower). Your shadow minions follow the normal minion rules: They have 1 HP, no damage modifier, and do not crit. Additionally, as an Action (1/turn) you may command ALL of your minions to move up to 6 spaces and attack an adjacent target. They abandon you immediately outside of combat.',
		actions: 1,
		roll: 'd12',
		onlyFor: 'Shadowmancer',
	},
	{
		name: 'Entice',
		school: 'Necrotic',
		tier: 0,
		desc: 'On a hit a target within Range 8 takes 1d4 damage (ignore armor) and moves 2 spaces nearer to you. High Levels: Increment the die size 1 step every 5 levels (d6 → d8 → d10 → d12).',
		actions: 1,
		roll: '1d4!',
	},
	{
		name: 'Withering Touch',
		school: 'Necrotic',
		tier: 0,
		desc: 'Touch a target and deal 1d12 damage. They are considered undead for 1 round. High Levels: +6 damage every 5 levels.',
		actions: 1,
		roll: '1d12!',
	},
	{
		name: 'Shadow Trap',
		school: 'Necrotic',
		tier: 1,
		desc: '(Concentration, up to 1 minute.) The next creature to move adjacent to you suffers 3d12 damage and a small or tiny creature is also Restrained by shadowy tendrils. Upcast: +1 size category and +1d12 damage when they escape.',
		actions: 2,
		roll: '3d12!',
	},
	{
		name: 'Dread Visage',
		school: 'Necrotic',
		tier: 2,
		desc: `(Reaction, self)  When attacked, Defend for free. Melee
			attackers are Frightened of you and suffer 1d12
			damage if they attack you this round. Costs 2 mana
			less while dying. Upcast: +2 damage, +2 armor`,
		actions: 1,
		roll: '1d12!',
	},
	{
		name: 'Vampiric Greed',
		school: 'Necrotic',
		tier: 3,
		desc: 'Gain 1 Wound. Deal 4d12 damage to all adjacent creatures, heal HP equal to the damage done. Any surviving creatures make a STR save, you gain 1 Wound for each creature that saves. Upcast: +1 save DC.',
		actions: 2,
		roll: '4d12',
	},
	{
		name: 'Greater Shadow',
		school: 'Necrotic',
		tier: 4,
		desc: 'Summon a 5d12 Greater Shadow minion (max 1) adjacent to you. When it dies, it explodes into 5 shadow minions (see Summon Shadow)—place them anywhere within 8 spaces. Upcast: +1d12 damage, +1 shadow on explosion.',
		actions: 2,
		roll: '5d12',
	},
	{
		name: 'Gangrenous Burst',
		school: 'Necrotic',
		tier: 5,
		desc: 'Damaged creatures within Reach 8 make STR save, made with disadvantage while Bloodied, or take 3d20 damage (ignoring armor), half on save. Upcast: +10 damage.',
		actions: 2,
		roll: '3d20',
	},
	{
		name: 'Unspeakable Word',
		school: 'Necrotic',
		tier: 6,
		desc: 'A target within Reach 8 takes d66 damage (with advantage, ignore armor, does not miss or crit) on a failed INT save. If they succeed, you each take half damage. The target has disadvantage if they are Bloodied or Frightened. Upcast: +1 save DC.',
		actions: 2,
		roll: 'd6,6,6rl1',
	},
	{
		name: 'Creeping Death',
		school: 'Necrotic',
		tier: 7,
		desc: 'Deal 4d20 damage to a creature within Reach 8. If this kills the creature, it violently erupts and you MUST deal the same amount of damage to another creature within Reach 8 of it that has not yet been damaged by this effect. Repeat until a creature survives this damage or no other creatures are in range. Upcast: +1d20 damage.',
		actions: 3,
		roll: '4d20!',
	},
];

export const lightningSpells: Spell[] = [
	{
		name: 'Zap',
		school: 'Lightning',
		tier: 0,
		desc: 'Deal 2d8 damage to a target within 90 ft. If this misses, the lightning fails to find ground and strikes you instead. High Levels: +4 damage every 5 levels.',
		actions: 1,
		roll: '2d8!',
	},
	{
		name: 'Overload',
		school: 'Lightning',
		tier: 0,
		desc: '(Can only be cast if you are charged.) Deal 2d8 damage to all other creatures within Reach 2 of you. High Levels: +4 damage every 5 levels.',
		actions: 1,
		roll: '2d8',
	},
	{
		name: 'Arc Lightning',
		school: 'Lightning',
		tier: 1,
		desc: 'Deal 3d8 damage to a target within Range 12. The bolt also strikes the next closest creature (could be friend or foe) to your target. If this attack misses, the lightning fails to find ground and strikes you instead. Upcast: +4 damage.',
		actions: 2,
		roll: '3d8!',
	},
	{
		name: 'Alacrity',
		school: 'Lightning',
		tier: 2,
		desc: 'As a reaction when attacked, Defend for free. After damage is dealt, you gain the Charged condition then teleport to anywhere in Range 4. Upcast: +4 Range.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Stormlash',
		school: 'Lightning',
		tier: 3,
		desc: 'In a line of lenght 12, deal 3d8+4 damage (ignoring metal armor). Surviving creatures are Dazed on a failed STR save, or Incapacitated instead for 1 of their turns if they fail by 5 or more. Creatures with a large amount of metal (e.g., armor or a longsword) roll with disadvantage. Upcast: +4 damage.',
		actions: 2,
		roll: '5d8',
	},
	{
		name: 'Electrickery',
		school: 'Lightning',
		tier: 4,
		desc: '(Reaction) When an ally is attacked, choose another creature within Range 8 to swap places with your ally on a failed WIL save (they become the new target). Costs 1 action while charged, ending the condition. Upcast: +2 range',
		actions: 3,
		roll: '',
	},
	{
		name: 'Electrocharge',
		school: 'Lightning',
		tier: 5,
		desc: '(Concentration, up to 1 minute.) A target you touch gains the Charged condition, +1 max Action, +5 Armor, double Speed, and advantage on DEX saves. Upcast: +1 minute duration.',
		actions: 2,
		roll: '',
	},
	{
		name: 'Ride the Lightning',
		school: 'Lightning',
		tier: 6,
		desc: 'Teleport up to 12 spaces away to a spot you can see. If a willing creature is there, swap places with them. Adjacent creatures take d88 damage. Surviving creatures must make a STR save or be hurled back 3 spaces, knocked Prone and deafened for 1 day. Upcast: +1 DC',
		actions: 3,
		roll: 'd8,8',
	},
	{
		name: 'Seething Storm',
		school: 'Lightning',
		tier: 9,
		desc: '(Concentration, up to 1 minute.) You become a cloud of tempestuous storm. You can fly, move for free once per round, and attacks against you are made with disadvantage. At the end of each of your turns, strike up to four creatures within Reach 4, with a bolt of lightning for d88 damage. A creature can only be struck once per round. +2 Reach and +2 number of bolts each round, costs 3 actions each round to maintain. Once you cast this spell, you must Safe Rest for one week before you can use it again.',
		actions: 3,
		roll: 'd8*10+d8',
	},
];

export const windSpells: Spell[] = [
	{
		name: 'Razor Wind',
		school: 'Wind',
		tier: 0,
		desc: 'Deal 1d4 slashing damage to up to 2 adjacent targets Range 12. Vicious (roll an additional die whenever this crits). High Levels: +2 damage every 5 levels.',
		actions: 1,
		roll: '1d4!v',
	},
	{
		name: 'Breath of Life',
		school: 'Wind',
		tier: 0,
		desc: 'Restore 1 HP to a Dying creature within Range 6. High Levels: +2 Range every 5 levels.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Vicious Mockery',
		school: 'Wind',
		tier: 0,
		desc: '(Songweaver Only.) Range 12. 1d4+INT psychic damage (ignores armor). On hit: the target is taunted during their next turn. High Levels: +2 damage every 5th level).',
		actions: 1,
		roll: '1d4!+[INT]',
		onlyFor: 'Songweaver',
	},
	{
		name: 'Blustery Gale',
		school: 'Wind',
		tier: 1,
		desc: 'Deal 3d4 slashing damage to a target within Range 12. Move a medium target 2 spaces; small/tiny targets twice as far. Advantage against flying or small/tiny targets. For each die you would roll due to force movement from this spell, deal +5 damage instead. Upcast: +1 movement.',
		actions: 2,
		roll: '3d4!',
	},
	{
		name: 'Barrier of Wind',
		school: 'Wind',
		tier: 2,
		desc: '(Reaction, when you would Defend.) Ranged attacks have disadvantage against you until the start of your next turn (including the triggering attack), then Defend for free. Upcast: +3 Armor.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Fly',
		school: 'Wind',
		tier: 3,
		desc: '(Concentration, up to 10 minutes.) Touch a creature, grant a flying speed of 12. Upcast: +1 target.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Eye of the Storm',
		school: 'Wind',
		tier: 4,
		desc: "Deal 4d4+10 bludgeoning damage to enemies within Reach 3. You may place surviving creatures anywhere within one space of the storm's reach on a failed STR save. Upcast: +1 Reach",
		actions: 2,
		roll: '4d4+10',
	},
	{
		name: 'Updraft',
		school: 'Wind',
		tier: 5,
		desc: 'Choose a 5x5 square area within Reach 12, enemy creatures there must roll a DEX save until they succeed. For each time they failed they take 1d6 damage and are landing prone. Upcast: +2 range, +1 area.',
		actions: 3,
		roll: '1d6',
	},
	{
		name: 'Thousand Cuts',
		school: 'Wind',
		tier: 6,
		desc: 'Target a creature within 90 ft. and roll 12d4. This attack does not miss, and EVERY die explodes on a 4. Also damages all enemies within 5 ft. of your target. Upcast: +5 ft. radius.',
		actions: 3,
		roll: 'd4,4,4rl1',
	},
	{
		name: 'Boisterous Winds',
		school: 'Wind',
		tier: 7,
		desc: '(Concentration, up to 1 minute.) You and up to 12 allies within Reach 12 gain: a flying speed of 12, can move up to their speed for free once each round, and ranged attacks have disadvantage against you. Upcast: +1 minute or +2 targets.',
		actions: 2,
		roll: '',
	},
];

export const utilitySpells: Spell[] = [
	{
		name: 'Kindle',
		school: 'Fire',
		tier: 0, // Utility spell, doesn't use mana
		desc: 'Use the power of fire magic to conjure a single minor visual illusion or make something warmer. Or: Ignite a small, unheld item within Range 6.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Fire Step',
		school: 'Fire',
		tier: 0, // Utility spell
		desc: 'Casting time: 1 minute. Teleport to a fire source you can see.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Firebrand',
		school: 'Fire',
		tier: 0, // Utility spell
		desc: 'Touch a surface and secretly mark it with a symbol or brief message. Speaking a chosen command word reveals the hidden mark.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Chillcraft',
		school: 'Ice',
		tier: 0, // Utility spell
		desc: 'Use your power over ice and water to: Chill. Harmlessly freeze, thaw, or move a bath-sized amount of water near you. Or: Craft. Conjure a sheet of opaque, mirror-like, or transparent ice no bigger than a window or small door.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Ice Disk',
		school: 'Ice',
		tier: 0, // Utility spell
		desc: 'Casting time: 1 minute. Conjure a disk of ice that floats just above the ground and follows you. It can carry up to 250lbs/115kg of weight for 1 hour or until you cast it again.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Wintry Scrying',
		school: 'Ice',
		tier: 0, // Utility spell
		desc: 'Casting time: 10 minutes. Turn a small patch of water into a reflective icy mirror. Looking through it grants you vision of any desired location near this same body of water for 10 minutes.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Spark Step',
		school: 'Lightning',
		tier: 0, // Utility spell
		desc: 'Teleport a metal object within Range 4',
		actions: 1,
		roll: '',
	},
	{
		name: "Tempest's Command",
		school: 'Lightning',
		tier: 0, // Utility spell
		desc: 'Harness the power of lightning magic to: Dispel a minor magical effect, or temporarily suppress a stronger one (the more powerful an enchantment, the shorter the duration), OR Voice of Thunder. For 1 minute your eyes flash with lightning and your voice is greatly amplified to a booming, thunder-like volume.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Spark Buddy',
		school: 'Lightning',
		tier: 0, // Utility spell
		desc: 'Casting time: 1 minute. Conjure a tiny electrical helper about the size of a squirrel for up to 1 hour. It can perform simple tasks you request of it such as fetch a small object (max 1 pound), open an unlocked door, glow brightly to illuminate a small area, or harmlessly shock creatures. If it takes damage or moves further than 6 spaces away from you, it dissipates into harmless sparks.',
		actions: 1,
		roll: '',
	},
	{
		name: 'False Face',
		school: 'Necrotic',
		tier: 0, // Utility spell
		desc: 'Casting time: 1 minute. Change your appearance to look like someone else for 10 minutes. You require a piece of that person.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Gravecraft',
		school: 'Necrotic',
		tier: 0, // Utility spell
		desc: 'Use your power over necrotic magic to: Gravemark. Soil a surface with blood, filth, or other disgusting things, OR Gravework. Casting time 1 minute: Shape/move a body-sized plot of earth.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Thought Leech',
		school: 'Necrotic',
		tier: 0, // Utility spell
		desc: 'Read the surface thoughts of a creature within Reach 6. Creatures can sense you doing this and may not like it.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Light',
		school: 'Radiant',
		tier: 0, // Utility spell
		desc: 'Cause an item to brightly glow with radiant light for as long as you hold it.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Beautify',
		school: 'Radiant',
		tier: 0, // Utility spell
		desc: 'Clean dirt or stains from an item, repair a small tear or break in a non-magical item, or conjure tiny beautiful things: flowers, butterflies, etc.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Bond of Peace',
		school: 'Radiant',
		tier: 0, // Utility spell
		desc: 'You may telepathically communicate simple thoughts or feelings with a friendly creature you can see. Alternatively, you can imbue your spoken words with calming magic, granting advantage on any check made to soothe anger or fear in a creatures who can hear you.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Wind Whisper',
		school: 'Wind',
		tier: 0, // Utility spell
		desc: 'You whisper a message into the wind and it will be secretly carried to a specified target within 100 miles/160 km.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Helpful Gust',
		school: 'Wind',
		tier: 0, // Utility spell
		desc: 'Gently move a tiny unheld item within Reach 6 in any direction; or generate an illusory scent.',
		actions: 1,
		roll: '',
	},
	{
		name: 'Feather Fall',
		school: 'Wind',
		tier: 0, // Utility spell (Reaction)
		desc: 'Reaction: cause a falling creature within Reach 6 to gently float to the ground unharmed.',
		actions: 1,
		roll: '',
	},
];
